// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skiplist.proto

package org.stez.utils;

public interface GetOptimalNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.stez.server.GetOptimalNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 最低分数
   * </pre>
   *
   * <code>int32 min_score = 1;</code>
   */
  int getMinScore();
}
