// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skiplist.proto

package org.stez.utils;

/**
 * <pre>
 * 请求消息：获取最优节点
 * </pre>
 *
 * Protobuf type {@code org.stez.server.GetOptimalNodeRequest}
 */
public  final class GetOptimalNodeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.stez.server.GetOptimalNodeRequest)
    GetOptimalNodeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetOptimalNodeRequest.newBuilder() to construct.
  private GetOptimalNodeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetOptimalNodeRequest() {
    minScore_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetOptimalNodeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            minScore_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.stez.utils.SkipListProto.internal_static_org_stez_server_GetOptimalNodeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.stez.utils.SkipListProto.internal_static_org_stez_server_GetOptimalNodeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.stez.utils.GetOptimalNodeRequest.class, org.stez.utils.GetOptimalNodeRequest.Builder.class);
  }

  public static final int MIN_SCORE_FIELD_NUMBER = 1;
  private int minScore_;
  /**
   * <pre>
   * 最低分数
   * </pre>
   *
   * <code>int32 min_score = 1;</code>
   */
  public int getMinScore() {
    return minScore_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (minScore_ != 0) {
      output.writeInt32(1, minScore_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (minScore_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, minScore_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.stez.utils.GetOptimalNodeRequest)) {
      return super.equals(obj);
    }
    org.stez.utils.GetOptimalNodeRequest other = (org.stez.utils.GetOptimalNodeRequest) obj;

    boolean result = true;
    result = result && (getMinScore()
        == other.getMinScore());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MIN_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + getMinScore();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.stez.utils.GetOptimalNodeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.stez.utils.GetOptimalNodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.stez.utils.GetOptimalNodeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 请求消息：获取最优节点
   * </pre>
   *
   * Protobuf type {@code org.stez.server.GetOptimalNodeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.stez.server.GetOptimalNodeRequest)
      org.stez.utils.GetOptimalNodeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.stez.utils.SkipListProto.internal_static_org_stez_server_GetOptimalNodeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.stez.utils.SkipListProto.internal_static_org_stez_server_GetOptimalNodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.stez.utils.GetOptimalNodeRequest.class, org.stez.utils.GetOptimalNodeRequest.Builder.class);
    }

    // Construct using org.stez.utils.GetOptimalNodeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      minScore_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.stez.utils.SkipListProto.internal_static_org_stez_server_GetOptimalNodeRequest_descriptor;
    }

    @java.lang.Override
    public org.stez.utils.GetOptimalNodeRequest getDefaultInstanceForType() {
      return org.stez.utils.GetOptimalNodeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.stez.utils.GetOptimalNodeRequest build() {
      org.stez.utils.GetOptimalNodeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.stez.utils.GetOptimalNodeRequest buildPartial() {
      org.stez.utils.GetOptimalNodeRequest result = new org.stez.utils.GetOptimalNodeRequest(this);
      result.minScore_ = minScore_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.stez.utils.GetOptimalNodeRequest) {
        return mergeFrom((org.stez.utils.GetOptimalNodeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.stez.utils.GetOptimalNodeRequest other) {
      if (other == org.stez.utils.GetOptimalNodeRequest.getDefaultInstance()) return this;
      if (other.getMinScore() != 0) {
        setMinScore(other.getMinScore());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.stez.utils.GetOptimalNodeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.stez.utils.GetOptimalNodeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int minScore_ ;
    /**
     * <pre>
     * 最低分数
     * </pre>
     *
     * <code>int32 min_score = 1;</code>
     */
    public int getMinScore() {
      return minScore_;
    }
    /**
     * <pre>
     * 最低分数
     * </pre>
     *
     * <code>int32 min_score = 1;</code>
     */
    public Builder setMinScore(int value) {
      
      minScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最低分数
     * </pre>
     *
     * <code>int32 min_score = 1;</code>
     */
    public Builder clearMinScore() {
      
      minScore_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.stez.server.GetOptimalNodeRequest)
  }

  // @@protoc_insertion_point(class_scope:org.stez.server.GetOptimalNodeRequest)
  private static final org.stez.utils.GetOptimalNodeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.stez.utils.GetOptimalNodeRequest();
  }

  public static org.stez.utils.GetOptimalNodeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetOptimalNodeRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetOptimalNodeRequest>() {
    @java.lang.Override
    public GetOptimalNodeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetOptimalNodeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetOptimalNodeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetOptimalNodeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.stez.utils.GetOptimalNodeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

