// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skiplist.proto

package org.stez.utils;

public interface OptimalNodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.stez.server.OptimalNodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 最优节点名称
   * </pre>
   *
   * <code>string node_name = 1;</code>
   */
  java.lang.String getNodeName();
  /**
   * <pre>
   * 最优节点名称
   * </pre>
   *
   * <code>string node_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeNameBytes();
}
