// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skiplist.proto

package org.stez.utils;

public final class SkipListProto {
  private SkipListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stez_server_GetOptimalNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stez_server_GetOptimalNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stez_server_OptimalNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stez_server_OptimalNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stez_server_UpdateNodeStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stez_server_UpdateNodeStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stez_server_UpdateNodeStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stez_server_UpdateNodeStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016skiplist.proto\022\017org.stez.server\"*\n\025Get" +
      "OptimalNodeRequest\022\021\n\tmin_score\030\001 \001(\005\"(\n" +
      "\023OptimalNodeResponse\022\021\n\tnode_name\030\001 \001(\t\"" +
      ";\n\027UpdateNodeStatusRequest\022\021\n\tnode_name\030" +
      "\001 \001(\t\022\r\n\005score\030\002 \001(\005\"+\n\030UpdateNodeStatus" +
      "Response\022\017\n\007success\030\001 \001(\0102\336\001\n\017SkipListSe" +
      "rvice\022`\n\016GetOptimalNode\022&.org.stez.serve" +
      "r.GetOptimalNodeRequest\032$.org.stez.serve" +
      "r.OptimalNodeResponse\"\000\022i\n\020UpdateNodeSta" +
      "tus\022(.org.stez.server.UpdateNodeStatusRe" +
      "quest\032).org.stez.server.UpdateNodeStatus" +
      "Response\"\000B!\n\016org.stez.utilsB\rSkipListPr" +
      "otoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_stez_server_GetOptimalNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_stez_server_GetOptimalNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stez_server_GetOptimalNodeRequest_descriptor,
        new java.lang.String[] { "MinScore", });
    internal_static_org_stez_server_OptimalNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_stez_server_OptimalNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stez_server_OptimalNodeResponse_descriptor,
        new java.lang.String[] { "NodeName", });
    internal_static_org_stez_server_UpdateNodeStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_stez_server_UpdateNodeStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stez_server_UpdateNodeStatusRequest_descriptor,
        new java.lang.String[] { "NodeName", "Score", });
    internal_static_org_stez_server_UpdateNodeStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_stez_server_UpdateNodeStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stez_server_UpdateNodeStatusResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
