// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skiplist.proto

package org.stez.utils;

public interface UpdateNodeStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.stez.server.UpdateNodeStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 操作是否成功
   * </pre>
   *
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
